name: Build macOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Add icon file
        run: |
          mkdir -p icons
          echo "<icon-file-content>" > icons/my_icon.icns  # 替换 <icon-file-content> 为你的图标内容

      - name: Build application
        run: pyinstaller --onefile --windowed --icon=icons/icon.icns wordpic.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: dist/wordpic.app
